const cards = [
  {
    title:
      'Charlottenburg-Wilmersdorf veröffentlicht Schätzungen statt Wahlergebnisse',
    subtitle: '',
    tags: ['data journalism', 'rbb|24', 'Wahlen 2021'],
    date: new Date(2021, 8, 30),
    url: 'https://www.rbb24.de/politik/wahl/abgeordnetenhaus/agh-2021/ergebnisse-bvv/berlin-wahl-bezirksverordnetenversammlung-charlottenburg-wilmersdorf-bvv.html',
    imageUrl: 'cards/card-rbb.png',
  },
  {
    title: 'Auffällig viele ungültige Stimmen in 99 Berliner Wahlbezirken',
    subtitle: '',
    tags: ['data journalism', 'rbb|24', 'Wahlen 2021'],
    date: new Date(2021, 8, 29),
    url: 'https://www.rbb24.de/politik/wahl/abgeordnetenhaus/agh-2021/beitraege/berlin-wahl-unregelmaessigkeiten-wahlfehler-falsche-stimmzettel.html',
    imageUrl: 'cards/card-rbb.png',
  },
  {
    title: 'Welche Parteien die treuesten Wähler und Wählerinnen haben',
    subtitle: '',
    tags: ['data visualisation', 'ternary charts', 'rbb|24', 'react', 'd3.js'],
    date: new Date(2021, 8, 23),
    url: 'https://www.rbb24.de/politik/wahl/abgeordnetenhaus/agh-2021/beitraege/berliner-superwahltag-2021-bundestag-abgeordnetenhaus-bezirksverordnetenversammlung-volksentscheid-stimmensplitting.html',
    imageUrl: 'cards/card-rbb.png',
  },
  {
    title: 'Wie Mütter und Väter zwei unterschiedliche Pandemien erlebten',
    subtitle: '',
    tags: [
      'data visualisation',
      'storytelling',
      'nominiert für den Reporter:innenpreis 2021',
      'rbb|24',
      'react',
      'd3.js',
    ],
    date: new Date(2021, 8, 8),
    url: 'https://www.rbb24.de/politik/thema/corona/beitraege/2021/09/lockdown-auswirkungen-gender-care-gap-muetter-vaeter-familie.html',
    imageUrl: 'cards/card-rbb.png',
  },
  {
    title: 'Switching the light off',
    subtitle: "Academic journals' impact factors without their star articles",
    tags: [
      'data visualisation',
      'design & development',
      'self-initiated',
      'd3.js',
      'svelte.js',
    ],
    date: new Date(2021, 1, 23),
    url: 'https://sophiamersmann.github.io/impact-factors/',
    imageUrl: 'cards/card-impact-factors.webp',
    githubUrl: 'https://github.com/sophiamersmann/impact-factors',
  },
  {
    title: 'kleineAnfragen visualisiert',
    subtitle:
      'Visualisierung kleiner und großer Anfragen aus dem Bundestag und aus den Landesparlamenten (Daten von kleineAnfragen.de)',
    tags: [
      'data visualisation',
      'design & development',
      'self-initiated',
      'd3.js',
      'Vue.js',
      'politics',
    ],
    date: new Date(2021, 0, 25),
    url: 'https://sophiamersmann.github.io/kleine-anfragen-visualised/',
    imageUrl: 'cards/card-kleine-anfragen.webp',
    githubUrl: 'https://github.com/sophiamersmann/kleine-anfragen-visualised',
  },
  {
    title: 'Minesweeper',
    subtitle: 'Built with Vue.js',
    tags: ['design & development', 'self-initiated', 'Vue.js', 'games'],
    date: new Date(2020, 9, 1),
    url: 'https://sophiamersmann.github.io/minesweeper/',
    imageUrl: 'cards/card-minesweeper.webp',
    githubUrl: 'https://github.com/sophiamersmann/minesweeper',
  },
  {
    title: 'Newcomer Parties To European Parliaments',
    subtitle:
      'A visualisation of parties elected into parliament for the first time',
    tags: [
      'data visualisation',
      'data analysis',
      'design & development',
      'self-initiated',
      'd3.js',
      'politics',
    ],
    date: new Date(2020, 7, 1),
    url: 'https://sophiamersmann.github.io/newcomer-parties/',
    imageUrl: 'cards/card-newcomer-parties.webp',
    githubUrl: 'https://github.com/sophiamersmann/newcomer-parties',
  },
  {
    title: 'Rummy Calendar',
    subtitle: 'Of weeks and months when all we had was playing cards',
    tags: [
      'data visualisation',
      'data collection & analysis',
      'design & development',
      'self-initiated',
      'd3.js',
      'corona',
    ],
    date: new Date(2020, 5, 1),
    url: 'https://sophiamersmann.github.io/rummy-calendar/',
    imageUrl: 'cards/card-rummy-calendar.webp',
    githubUrl: 'https://github.com/sophiamersmann/rummy-calendar',
  },
  {
    title: 'ProteinLens',
    subtitle:
      'A web server to explore allosteric communication within a protein (developed in the Yaliraki Group at Imperial College London)',
    tags: [
      'webserver',
      'data visualisation',
      'Django',
      'd3.js',
      'bioinformatics',
      'Imperical College London',
    ],
    date: new Date(2019, 8, 1),
    url: 'https://proteinlens.io/',
    imageUrl: 'cards/card-proteinlens.webp',
    githubUrl: null,
  },
  {
    title:
      'Posterior Error Probability Estimation for Peptide Search Engine Results in OpenMS',
    subtitle: 'As part of Google Summer of Code 2018 (Master thesis)',
    tags: [
      'research',
      'master thesis',
      'data visualisation',
      'd3.js',
      'Imperical College London',
    ],
    date: new Date(2020, 8, 1),
    url: 'https://sophiamersmann.github.io/master-thesis/',
    imageUrl: 'cards/card-master-thesis.webp',
    githubUrl: 'https://github.com/sophiamersmann/master-thesis',
  },
];

export default cards;
