const cards = [
  {
    title: 'Switching the light off',
    subtitle: "Academic journals' impact factors without their star articles",
    tags: [
      'data visualisation',
      'design & development',
      'self-initiated',
      'd3.js',
      'svelte.js',
    ],
    date: new Date(2021, 1, 23),
    url: 'https://sophiamersmann.github.io/impact-factors/',
    imageUrl: 'cards/card-impact-factors.webp',
    githubUrl: 'https://github.com/sophiamersmann/impact-factors',
  },
  {
    title: 'kleineAnfragen visualisiert',
    subtitle:
      'Visualisierung kleiner und großer Anfragen aus dem Bundestag und aus den Landesparlamenten (Daten von kleineAnfragen.de)',
    tags: [
      'data visualisation',
      'design & development',
      'self-initiated',
      'd3.js',
      'Vue.js',
      'politics',
    ],
    date: new Date(2021, 0, 25),
    url: 'https://sophiamersmann.github.io/kleine-anfragen-visualised/',
    imageUrl: 'cards/card-kleine-anfragen.webp',
    githubUrl: 'https://github.com/sophiamersmann/kleine-anfragen-visualised',
  },
  {
    title: 'Minesweeper',
    subtitle: 'Built with Vue.js',
    tags: ['design & development', 'self-initiated', 'Vue.js', 'games'],
    date: new Date(2020, 9, 1),
    url: 'https://sophiamersmann.github.io/minesweeper/',
    imageUrl: 'cards/card-minesweeper.webp',
    githubUrl: 'https://github.com/sophiamersmann/minesweeper',
  },
  {
    title: 'Newcomer Parties To European Parliaments',
    subtitle:
      'A visualisation of parties elected into parliament for the first time',
    tags: [
      'data visualisation',
      'data analysis',
      'design & development',
      'self-initiated',
      'd3.js',
      'politics',
    ],
    date: new Date(2020, 7, 1),
    url: 'https://sophiamersmann.github.io/newcomer-parties/',
    imageUrl: 'cards/card-newcomer-parties.webp',
    githubUrl: 'https://github.com/sophiamersmann/newcomer-parties',
  },
  {
    title: 'Rummy Calendar',
    subtitle: 'Of weeks and months when all we had was playing cards',
    tags: [
      'data visualisation',
      'data collection & analysis',
      'design & development',
      'self-initiated',
      'd3.js',
      'corona',
    ],
    date: new Date(2020, 5, 1),
    url: 'https://sophiamersmann.github.io/rummy-calendar/',
    imageUrl: 'cards/card-rummy-calendar.webp',
    githubUrl: 'https://github.com/sophiamersmann/rummy-calendar',
  },
  {
    title: 'ProteinLens',
    subtitle:
      'A web server to explore allosteric communication within a protein (developed in the Yaliraki Group at Imperial College London)',
    tags: [
      'webserver',
      'data visualisation',
      'Django',
      'd3.js',
      'bioinformatics',
      'Imperical College London',
    ],
    date: new Date(2019, 8, 1),
    url: 'https://proteinlens.io/',
    imageUrl: 'cards/card-proteinlens.webp',
    githubUrl: null,
  },
  {
    title:
      'Posterior Error Probability Estimation for Peptide Search Engine Results in OpenMS',
    subtitle: 'As part of Google Summer of Code 2018 (Master thesis)',
    tags: [
      'research',
      'master thesis',
      'data visualisation',
      'd3.js',
      'Imperical College London',
    ],
    date: new Date(2020, 8, 1),
    url: 'https://sophiamersmann.github.io/master-thesis/',
    imageUrl: 'cards/card-master-thesis.webp',
    githubUrl: 'https://github.com/sophiamersmann/master-thesis',
  },
];

export default cards;
